### ISSUE TITLE
Debian packager request: Please tag your releases

### ISSUE THREAD

**Issue by dod38fr** [jonathanstowe/License-SPDX#4]
Hello

In Debian, we have a toolset (i.e. [uscan](https://manpages.debian.org/unstable/devscripts/uscan.1.en.html)) to track upstream release that work on GitHub tags.

Without release tags, the tracking tools are not working and we are not aware when a new release is mage. Which means Debian packages will lag behind your releases.

So please tag at least the last release and any future release.

All the best

Dod (for Debian)

**Comment by dod38fr** [comment]
Sorry, I got confused between lack of tags and lack of release. I see that tag 3.17.0 does exits.

I'm closing this issue, sorry for the noise.

**Comment by jonathanstowe** [comment]
Yeah I tag the code when I make a release as part of the workflow, but creating a "release" on GH is largely redundant as people will use other tools rather than download a tarball from here.

**Comment by dod38fr** [comment]
Having a tag is enough for Debian. 

Thanks for the follow-up.
